# Generated by Django 4.1.3 on 2022-11-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_model',
            name='country',
            field=models.CharField(choices=[('mumbai', 'mumbai'), ('hyderabad', 'hyderabad'), ('chennai', 'chennai'), ('bangalore', 'bangalore'), ('andhrapradesh', 'andhrapradesh')], max_length=256),
        ),
    ]
