# Generated by Django 4.1.3 on 2022-11-23 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('profile_picture', models.ImageField(upload_to='media')),
                ('country', models.CharField(blank=True, choices=[('mumbai', 'mumbai'), ('hyderabad', 'hyderabad'), ('chennai', 'chennai'), ('bangalore', 'bangalore'), ('andhrapradesh', 'andhrapradesh')], max_length=256)),
            ],
        ),
    ]
